# Generated by Django 3.2.6 on 2022-03-28 07:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profpic', models.ImageField(default='default.png', null=True, upload_to='profile_images')),
                ('bio', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('favorite_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('fav_genres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.genre')),
                ('streaming_services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.streamingservices')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
