# Generated by Django 3.2.6 on 2022-04-07 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesList',
            fields=[
                ('movieid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('genre_list', models.JSONField(max_length=100)),
                ('release_date', models.DateTimeField()),
                ('poster_path', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WatchListData',
            fields=[
                ('watchid', models.AutoField(primary_key=True, serialize=False)),
                ('mov_show_id', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('media_type', models.IntegerField(blank=True, choices=[(1, 'Movie'), (2, 'TV')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_list', models.JSONField(blank=True, default=list, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavoritesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favs_list', models.JSONField(blank=True, default=list, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profpic', models.ImageField(default='default.png', null=True, upload_to='profile_images')),
                ('bio', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('fav_genres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.genre')),
                ('streaming_services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.streamingservices')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteListData',
            fields=[
                ('favid', models.AutoField(primary_key=True, serialize=False)),
                ('mov_show_id', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('media_type', models.IntegerField(blank=True, choices=[(1, 'Movie'), (2, 'TV')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='watchlistdata',
            constraint=models.UniqueConstraint(fields=('user', 'mov_show_id', 'media_type'), name='watchlist_constraint'),
        ),
        migrations.AddConstraint(
            model_name='favoritelistdata',
            constraint=models.UniqueConstraint(fields=('user', 'mov_show_id', 'media_type'), name='fav_constraint'),
        ),
    ]
