# Generated by Django 3.2.12 on 2022-03-29 22:02

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesList',
            fields=[
                ('movieid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('genre_list', models.JSONField(max_length=100)),
                ('release_date', models.DateTimeField()),
                ('poster_path', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profpic', models.ImageField(default='default.png', null=True, upload_to='profile_images')),
                ('bio', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('fav_genres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.genre')),
                ('streaming_services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.streamingservices')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
