# Generated by Django 3.2.6 on 2022-04-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220404_1039'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoritelistdata',
            name='mov_show_id_media',
        ),
        migrations.AddConstraint(
            model_name='favoritelistdata',
            constraint=models.UniqueConstraint(fields=('user', 'mov_show_id', 'media_type'), name='mov_show_id_media'),
        ),
    ]
