# Generated by Django 3.2.6 on 2022-03-30 05:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_favoritelist_movieslist_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='favorites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=list), blank=True, default=list, null=True, size=None),
        ),
    ]
