# Generated by Django 3.2.6 on 2022-05-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220502_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaylist',
            name='comments_on',
            field=models.BooleanField(default=True),
        ),
    ]
