# Generated by Django 3.2.6 on 2022-05-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220506_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Restricted')], default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Restricted')], default=0),
        ),
        migrations.AlterField(
            model_name='userplaylist',
            name='status',
            field=models.BooleanField(choices=[(0, 'Open'), (1, 'Restricted')], default=0),
        ),
        migrations.AlterField(
            model_name='userreviewpost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Restricted')], default=0),
        ),
    ]
