# Generated by Django 3.2.6 on 2022-03-31 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_favoritelistdata_movieslist_profile_userfavoriteslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelistdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
