# Generated by Django 3.2.6 on 2022-01-31 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='genre',
        ),
    ]
