# Generated by Django 3.2.6 on 2022-04-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220414_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplaylist',
            name='playlist_follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='app.UserPlaylist'),
        ),
        migrations.AlterField(
            model_name='userplaylist',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
