# Generated by Django 3.2.6 on 2022-04-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220415_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userplaylist',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='userplaylist',
            name='cover_img',
            field=models.ImageField(default='media/default.png', null=True, upload_to='cover_images'),
        ),
    ]
