# Generated by Django 3.2.6 on 2022-04-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220422_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaylist',
            name='user_pl_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
