# Generated by Django 3.2.6 on 2022-04-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220418_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplaylist',
            name='comments_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userplaylist',
            name='cover_img',
            field=models.ImageField(default='default.png', null=True, upload_to='cover_images'),
        ),
    ]
