# Generated by Django 3.2.6 on 2022-04-28 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlaylistPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='UserStatusPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='playlist',
        ),
        migrations.AddField(
            model_name='userplaylist',
            name='share_list',
            field=models.ManyToManyField(default=False, related_name='sharing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userplaylistdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
        migrations.AddField(
            model_name='userplaylistpost',
            name='playlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl_posts', to='app.userplaylist'),
        ),
        migrations.AddField(
            model_name='userplaylistpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.userplaylistpost'),
            preserve_default=False,
        ),
    ]
