# Generated by Django 3.2.6 on 2022-02-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_name_genre_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('display_priority', models.IntegerField()),
                ('logo_path', models.CharField(max_length=100)),
                ('provider_name', models.CharField(max_length=50)),
                ('provider_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
