# Generated by Django 2.1.15 on 2022-03-28 18:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_favorite_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
    ]
