# Generated by Django 3.2.6 on 2022-03-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220328_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesList',
            fields=[
                ('movieid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('genre_list', models.JSONField(max_length=100)),
                ('release_date', models.DateTimeField()),
                ('poster_path', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
            ],
        ),
    ]
