# Generated by Django 2.1.15 on 2022-03-28 18:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220328_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
