# Generated by Django 3.2.6 on 2022-02-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220201_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StreamingProviderRegion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('countryABR', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Providers',
            new_name='StreamingProviders',
        ),
    ]
