# Generated by Django 3.2.6 on 2022-02-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220201_1349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StreamingProviderRegion',
            new_name='StreamingRegion',
        ),
    ]
