# Generated by Django 3.2.6 on 2022-02-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
