# Generated by Django 3.2.6 on 2022-02-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamingregion',
            name='id',
        ),
        migrations.AlterField(
            model_name='streamingregion',
            name='iso_3166_1',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
