# Generated by Django 3.2.6 on 2022-02-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220204_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingServices',
            fields=[
                ('display_priority', models.IntegerField()),
                ('logo_path', models.CharField(max_length=200)),
                ('provider_name', models.CharField(max_length=150)),
                ('provider_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UsCerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=10)),
                ('meaning', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='StreamingProviders',
        ),
    ]
