# Generated by Django 3.2.6 on 2022-02-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220204_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='streamingregion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='streamingservices',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uscerts',
            options={'managed': False},
        ),
    ]
