# Generated by Django 3.2.6 on 2022-02-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220207_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streamingurls',
            fields=[
                ('provider_id', models.IntegerField(primary_key=True, serialize=False)),
                ('url_path', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'app_streamingurls',
                'managed': False,
            },
        ),
    ]
