# Generated by Django 2.1.15 on 2022-03-25 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_streamingurls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='profpic',
        ),
        migrations.AddField(
            model_name='profile',
            name='fav_genres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Genre'),
        ),
        migrations.AddField(
            model_name='profile',
            name='streaming_services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StreamingServices'),
        ),
    ]
