# Generated by Django 2.1.15 on 2022-03-26 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_auto_20220324_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fav_movie_show_id', models.BigIntegerField()),
                ('share', models.BooleanField()),
                ('private', models.BooleanField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('user_fav_like_count', models.BigIntegerField(default='0')),
                ('favorites', models.ManyToManyField(default=None, related_name='favorite', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_likes', models.ManyToManyField(default=None, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('watch_movie_show_id', models.BigIntegerField()),
                ('share', models.BooleanField()),
                ('private', models.BooleanField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('watch_like_count', models.BigIntegerField(default='0')),
                ('add_watch', models.ManyToManyField(default=None, related_name='addwatch', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watch_like', models.ManyToManyField(default=None, related_name='watchlike', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
