# Generated by Django 2.1.15 on 2022-03-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220326_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritelist',
            old_name='fav_movie_show_id',
            new_name='movie_show_id',
        ),
    ]
