# Generated by Django 2.1.15 on 2022-03-26 21:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220326_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritelist',
            options={},
        ),
        migrations.RemoveField(
            model_name='favoritelist',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='favoritelist',
            name='movie_show_id',
        ),
        migrations.RemoveField(
            model_name='favoritelist',
            name='private',
        ),
        migrations.RemoveField(
            model_name='favoritelist',
            name='share',
        ),
        migrations.RemoveField(
            model_name='favoritelist',
            name='user_fav_like_count',
        ),
        migrations.RemoveField(
            model_name='favoritelist',
            name='user_likes',
        ),
        migrations.RemoveField(
            model_name='favoritelist',
            name='favorites',
        ),
        migrations.AddField(
            model_name='favoritelist',
            name='favorites',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=2),
            preserve_default=False,
        ),
    ]
